// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import PasswordController from "./password_controller"
application.register("password", PasswordController)

import PasswordCopyMessageController from "./password_copy_message_controller"
application.register("passwordCopyMessage", PasswordCopyMessageController)
